namespace Clinics_Websites_Shops.Utilities
{
    public class SD
    {
            // Areas
            public const string AdminArea = "Admin";
            public const string CustomerArea = "Customer";
            public const string IdentityArea = "Identity";
            public const string TenanceArea = "Tenance";


            // Controllers
            public const string CategoryController = "Department";
            public const string HomeController = "Home";

            // Actions
            public const string NotFoundPage = "NotFoundPage";

            //Roles
            public const string SuperAdminRole = "SuperAdminRole";
            public const string AdminRole = "AdminRole";
            public const string CompanyRole = "CompanyRole";
            public const string CustomerRole = "CustomerRole";

    }
}
