-- Script to create a new tenant and admin user
-- Tenant: test.localhost
-- Admin Email: test@test.com
-- Admin Password: 123456

-- ============================================
-- STEP 1: Create Tenant in Master Database
-- ============================================

USE ClinicsMaster;

-- Generate a unique tenant ID
SET @tenantId = UUID();

-- Insert tenant record
INSERT INTO Tenants (TId, Name, Domain, ConnectionString, Status, Locals, CreatedAt)
VALUES (
    @tenantId,
    'Test Clinic',
    'test.localhost',
    'Server=localhost;Port=3306;Database=ClinicsWebsiteShops;User=root;Password=;',
    1,
    'en,ar',
    CURRENT_TIMESTAMP(6)
);

SELECT 'Tenant created successfully!' as Message;
SELECT * FROM Tenants WHERE TId = @tenantId;

-- ============================================
-- STEP 2: Create Admin User in Tenant Database
-- ============================================

USE ClinicsWebsiteShops;

-- Note: The password hash for '123456' needs to be generated by ASP.NET Identity
-- We'll create the user through a C# script instead

SELECT 'Please run the C# script to create the admin user with proper password hashing' as Message;

